Tailwind migration
bellshade/bellshade.github.io pull request #23
Opened 2021-09-27 13:30 UTC by feri-irawan

- [x] Migrasi ke TailwindCSS
- [x] Mengubah tampilan nama anggota di `.team-card` (muncul saat hover)

Web test: https://feri-irawan.github.io/bellshade.github.io/

2021-09-27 13:45 UTC, reacto11mecha requested changes
![Screenshot_20210927-203814_Chrome](https://user-images.githubusercontent.com/48118327/134920234-eae72842-2c1f-4b61-8974-a1c2796a6270.jpg)

Kurang responsive sih, dia agak bablas.

![Screenshot_20210927-203828_Chrome](https://user-images.githubusercontent.com/48118327/134920598-e5e78b8e-f4bb-4cea-ab37-d6f326a7b0bf.jpg)
![Screenshot_20210927-203834_Chrome](https://user-images.githubusercontent.com/48118327/134920610-23d0f17f-3b1e-44b1-b55d-40817b9f5232.jpg)
![Screenshot_20210927-203846_Chrome](https://user-images.githubusercontent.com/48118327/134920617-1d44e578-683e-4c19-b01d-2cbba1080fd3.jpg)

Nama juga agak bablas dari cardnya, terus juga mungkin kalo di handphone ga usah di hover, langsung muncul aja.

2021-09-27 14:48 UTC, yezki requested changes
Pelan2 aja diedit mas @feri-irawan untuk tooltip namanya. Keliatannya masih overflow ya di layar mobile.

2021-09-27 14:51 UTC, yezki commented
Oh iya, di layar desktop tooltipnya jg terlalu panjang ya. Karena tiap nama beda panjangnya, coba dibuat jg widthnya jd auto mas @feri-irawan.

2021-09-28 05:55 UTC, feri-irawan commented
- [x] Grid team card
- [x] Tooltip team card
Memperbaiki grid dan tooltip team card yg membuatnya tidak responsive.

Sip sekarang sudah responsive:

![Screenshot_20210928_134934](https://user-images.githubusercontent.com/57158078/135030828-575eb2f4-3e56-4204-938d-0e489e9ece40.jpg)
![Screenshot_20210928_134923](https://user-images.githubusercontent.com/57158078/135030834-5dd2fa3d-76e1-403d-9c90-a040d85c5b9e.jpg)
![Screenshot_20210928_134904](https://user-images.githubusercontent.com/57158078/135030848-ada970b3-c485-4088-bc91-bc49e251f8cb.jpg)

2021-09-28 06:01 UTC, reacto11mecha approved these changes
Sip :+1: , dah responsive

2021-09-28 09:29 UTC, yezki commented
![Screenshot_2021-09-28_16-26-00](https://user-images.githubusercontent.com/54763039/135061302-0c74cb60-e2f0-4f83-b583-8ea9a8a720dc.png)

Profile picturenya yg terakhir kok gak ketengah ya mas @feri-irawan kalau cuma 1?

2021-09-28 09:37 UTC, yezki requested changes
Ya mgkin itu aja sih mas @feri-irawan, profile picturenya gak ketengah utk yg elemen terakhir (kalau cuma 1) di layar mobile.

2021-09-29 08:55 UTC, yezki commented
![Screenshot_2021-09-29_15-54-16](https://user-images.githubusercontent.com/54763039/135236344-14b52cc6-f4fa-4691-9364-a6e8a05cede8.png)

Lah, ternyata yg didesktop jg sama, blm ketengah.. :smile:

2021-09-29 17:08 UTC, feri-irawan commented
@yezki sebenarnya saya mau buat ke tengah, tapi tidak bisa...

2021-09-30 00:58 UTC, slowy07 approved these changes
@bellshade/webpage-team

2021-09-30 02:25 UTC, yezki approved these changes

2021-09-30 03:14 UTC, merged

2021-09-30 04:34 UTC, nomadkode commented
noice :+1