Menambahkan Meta SEO dan Menggunakan :where() di CSS
bellshade/bellshade.github.io pull request #28
Opened 2021-09-30 22:40 UTC by mzaini30

2021-09-30 23:24 UTC, reacto11mecha requested changes

2021-09-30 23:24 UTC, reacto11mecha commented on index.html
> +    <meta name="description" content='Learn with Our Community' />
Mungkin ini digantinya gini aja

```suggestion
    <meta name="description" content="Komunitas untuk mengelola dan menulis kode untuk proyek pendidikan sumber terbuka Indonesia" />
```

2021-09-30 23:24 UTC, reacto11mecha commented on index.html
> +    <meta property="og:description" content='Learn with Our Community' />
```suggestion
    <meta property="og:description" content="Komunitas untuk mengelola dan menulis kode untuk proyek pendidikan sumber terbuka Indonesia" />
```

Yang ini juga sama

2021-09-30 23:35 UTC, reacto11mecha commented
Terus juga mau saran, gambar open graphnya bisa diganti sama gambar yang udah ada aja, soalnya itu ada logo bellshade asli + tulisannya

2021-10-01 00:44 UTC, mzaini30 commented
> Terus juga mau saran, gambar open graphnya bisa diganti sama gambar yang udah ada aja, soalnya itu ada logo bellshade asli + tulisannya

Ada kah di situ ya? Coba nanti tak cek.

2021-10-01 00:49 UTC, reacto11mecha commented
> > Terus juga mau saran, gambar open graphnya bisa diganti sama gambar yang udah ada aja, soalnya itu ada logo bellshade asli + tulisannya
> 
> Ada kah di situ ya? Coba nanti tak cek.

https://media.discordapp.net/attachments/891222600422936616/892682527720996884/unknown.png

Mungkin kalo mau ukurannya dibikin lebar ga ngapa sih, kayak open graph github kalo ngasi issue atau repo gitu modelannya

2021-10-01 00:58 UTC, feri-irawan commented
> Terus juga mau saran, gambar open graphnya bisa diganti sama gambar yang udah ada aja, soalnya itu ada logo bellshade asli + tulisannya

Udh cocok sih, om, karna isi web nya masih homepage jadi logo aja..

2021-10-01 01:00 UTC, feri-irawan commented on index.html
> +    <meta name="description" content='Learn with Our Community' />
Iya gini aja, tag linenya di masukin ke tag `title` tapi untuk OG nya simpan di `og:title`

2021-10-01 01:04 UTC, mzaini30 commented
> > > Terus juga mau saran, gambar open graphnya bisa diganti sama gambar yang udah ada aja, soalnya itu ada logo bellshade asli + tulisannya
> > 
> > 
> > Ada kah di situ ya? Coba nanti tak cek.
> 
> https://media.discordapp.net/attachments/891222600422936616/892682527720996884/unknown.png
> 
> Mungkin kalo mau ukurannya dibikin lebar ga ngapa sih, kayak open graph github kalo ngasi issue atau repo gitu modelannya.
> 
> Btw udah ada preview webnya nggak ? Sekalian dong biar bisa diliat

Belum sih. Nanti lah.

2021-10-01 01:06 UTC, mzaini30 commented
> > > Terus juga mau saran, gambar open graphnya bisa diganti sama gambar yang udah ada aja, soalnya itu ada logo bellshade asli + tulisannya
> > 
> > 
> > Ada kah di situ ya? Coba nanti tak cek.
> 
> https://media.discordapp.net/attachments/891222600422936616/892682527720996884/unknown.png
> 
> Mungkin kalo mau ukurannya dibikin lebar ga ngapa sih, kayak open graph github kalo ngasi issue atau repo gitu modelannya.
> 
> Btw udah ada preview webnya nggak ? Sekalian dong biar bisa diliat

Eh itu gambarnya besar kah resolusinya? Loading eh ngeloadnya.

2021-10-01 01:07 UTC, mzaini30 commented
> > > Terus juga mau saran, gambar open graphnya bisa diganti sama gambar yang udah ada aja, soalnya itu ada logo bellshade asli + tulisannya
> > 
> > 
> > Ada kah di situ ya? Coba nanti tak cek.
> 
> https://media.discordapp.net/attachments/891222600422936616/892682527720996884/unknown.png
> 
> Mungkin kalo mau ukurannya dibikin lebar ga ngapa sih, kayak open graph github kalo ngasi issue atau repo gitu modelannya.
> 
> Btw udah ada preview webnya nggak ? Sekalian dong biar bisa diliat

Aku resize jadi 800px.

2021-10-01 01:08 UTC, manh21 commented
> > > Terus juga mau saran, gambar open graphnya bisa diganti sama gambar yang udah ada aja, soalnya itu ada logo bellshade asli + tulisannya
> > 
> > 
> > Ada kah di situ ya? Coba nanti tak cek.
> 
> https://media.discordapp.net/attachments/891222600422936616/892682527720996884/unknown.png
> 
> Mungkin kalo mau ukurannya dibikin lebar ga ngapa sih, kayak open graph github kalo ngasi issue atau repo gitu modelannya.
> 
> Btw udah ada preview webnya nggak ? Sekalian dong biar bisa diliat

bisa buat gambar baru, yang original terlalu besar 2k x 2k di buat jadi 200 x 200

2021-10-01 01:08 UTC, feri-irawan commented
> https://media.discordapp.net/attachments/891222600422936616/892682527720996884/unknown.png
> 
> Mungkin kalo mau ukurannya dibikin lebar ga ngapa sih, kayak open graph github kalo ngasi issue atau repo gitu modelannya.
> 
> Btw udah ada preview webnya nggak ? Sekalian dong biar bisa diliat

Klo dikasi ukuran di `og:image:width` dan `og:image:height` kayaknya bisa untuk Facebook, Discord, klo untuk WhatsApp kurang tau juga soalnya dia pakai suka ngecrop gambar nya jadi kotak

2021-10-01 01:12 UTC, mzaini30 commented
Sudah kuubah og:image nya. Monggo dicek.

2021-10-01 11:37 UTC, reacto11mecha requested changes

2021-10-01 11:37 UTC, reacto11mecha commented on index.html
> +    <meta property="og:image" content='https://cdn.statically.io/img/media.discordapp.net/w=800/attachments/891222600422936616/892682527720996884/unknown.png' />
Untuk gambar bisa aja gini sih, menurutku oke aja cuman pakenya tanda petik dua `"`

```suggestion
    <meta property="og:image" content="https://cdn.statically.io/img/media.discordapp.net/w=800/attachments/891222600422936616/892682527720996884/unknown.png" />
```

2021-10-01 11:37 UTC, reacto11mecha commented on index.html
> +    <meta property="og:image:height" content="800" />
Kalo dari gambar yang cdn staticcally, ukurannya 800x856

```suggestion
    <meta property="og:image:height" content="856" />
```

2021-10-01 12:59 UTC, reacto11mecha approved these changes

2021-10-01 19:08 UTC, nomadkode approved these changes
LGTM

2021-10-02 02:34 UTC, feri-irawan approved these changes

2021-10-02 03:24 UTC, merged