fix: size navbar and added scrollbar
bellshade/bellshade.github.io pull request #33
Opened 2021-10-02 13:22 UTC by riyaraa

2021-10-02 16:35 UTC, slowy07 reviewed
request @bellshade/webpage-team

2021-10-02 16:59 UTC, riyaraa commented
maaf, saya push nya ke main soalnya tadi belum settings default branch nya, saya close pull atau tidak perlu ya?

2021-10-03 00:54 UTC, reacto11mecha commented
Nggak usah, sekarang tolong deploy previewnya ke repo fork punya mas sendiri

`npm run deploy`

Terus di setting juga di repo fork punya mas branch nya ke `gh-pages`

Kirim link previewnya kesini

2021-10-03 02:21 UTC, riyaraa commented
> Nggak usah, sekarang tolong deploy previewnya ke repo fork punya mas sendiri
> 
> `npm run deploy`
> 
> Terus di setting juga di repo fork punya mas branch nya ke `gh-pages`
> 
> Kirim link previewnya kesini

maaf mas mungkin link previewnya masih di local ya, sepert ini kan ya http://192.168.1.5:3000/ udah saya  settings juga hasil fork branch nya ke `gh pages`

2021-10-03 02:26 UTC, slowy07 commented
buat aj preview berupa screenshoot perubahan dari kak @riyaraa klo tidak memungkinkan menggunakan gitpages, tapi kami tetap menyarankan menggunakan gitpages untuk hasil dari perubahannya, terima kasih kak !

2021-10-03 02:37 UTC, riyaraa commented
> buat aj preview berupa screenshoot perubahan dari kak @riyaraa klo tidak memungkinkan menggunakan gitpages, tapi kami tetap menyarankan menggunakan gitpages untuk hasil dari perubahannya, terima kasih kak !

oke sudah nih mas, https://riyaraa.github.io/bellshade.github.io/

2021-10-03 02:37 UTC, reacto11mecha commented
> > buat aj preview berupa screenshoot perubahan dari kak @riyaraa klo tidak memungkinkan menggunakan gitpages, tapi kami tetap menyarankan menggunakan gitpages untuk hasil dari perubahannya, terima kasih kak !
> 
> oke sudah nih mas, https://riyaraa.github.io/bellshade.github.io/

Oke

2021-10-03 02:41 UTC, reacto11mecha requested changes
![Screenshot_20211003-093940_Chrome](https://user-images.githubusercontent.com/48118327/135737487-51d18cb9-abac-4cf2-9b47-817add39d2b0.jpg)

Pas dimobile, logo bellshadenya agak ketutupan. Coba difix sekalian bawa fitur yang mas udah buat sebelumnya

2021-10-03 02:42 UTC, riyaraa commented
> ![Screenshot_20211003-093940_Chrome](https://user-images.githubusercontent.com/48118327/135737487-51d18cb9-abac-4cf2-9b47-817add39d2b0.jpg)
> 
> Pas dimobile, logo bellshadenya agak ketutupan. Coba difix sekalian bawa fitur yang mas udah buat sebelumnya

wah iya mas, kemarin sih saya test di local saya aman di mobilenya, okeoke saya solve dulu

2021-10-03 02:45 UTC, reacto11mecha commented
> > ![Screenshot_20211003-093940_Chrome](https://user-images.githubusercontent.com/48118327/135737487-51d18cb9-abac-4cf2-9b47-817add39d2b0.jpg)
> > Pas dimobile, logo bellshadenya agak ketutupan. Coba difix sekalian bawa fitur yang mas udah buat sebelumnya
> 
> wah iya mas, kemarin sih saya test di local saya aman di mobilenya, okeoke saya solve dulu

Sip, untuk di desktop udah aman sih tinggal mobile aja yang dibenerin

2021-10-03 03:01 UTC, riyaraa commented
![screencapture-localhost-3000-2021-10-03-10_00_24](https://user-images.githubusercontent.com/50629099/135737865-7ab8c2d7-a26b-4bce-9420-ee7eb9b75541.png)

disaya udah oke nih mas, saya coba deploy lagi ya

2021-10-03 04:02 UTC, LevianthProject commented
wah sudah mangtap ya :wpugege:

2021-10-03 04:02 UTC, closed without merging